-- ============================================
-- Migration: Pembuatan tabel garansi
-- ============================================

CREATE TABLE IF NOT EXISTS public.garansi (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_transaksi character varying(100) NOT NULL,
    nama_pelanggan character varying(256) NOT NULL,
    nomor_whatsapp character varying(50) NOT NULL,
    imei1 character varying(100),
    imei2 character varying(100),
    nomor_seri character varying(100),
    merk_tipe character varying(256) NOT NULL,
    warna_kapasitas character varying(256),
    tanggal_pembelian timestamp without time zone DEFAULT now() NOT NULL,
    durasi_garansi character varying(100) NOT NULL,
    jenis_garansi character varying(100) NOT NULL,
    status_garansi character varying(100) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);

-- Enable RLS (Row Level Security) if needed or just grant access
ALTER TABLE public.garansi ENABLE ROW LEVEL SECURITY;

-- Drop old policies if they exist
DROP POLICY IF EXISTS "Allow read for authenticated users" ON public.garansi;
DROP POLICY IF EXISTS "Allow write for authenticated users" ON public.garansi;
DROP POLICY IF EXISTS "allow_all_garansi" ON public.garansi;

-- Create correct policy for both anon and authenticated
CREATE POLICY "allow_all_garansi" ON public.garansi
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
