-- ============================================
-- Migration: Tambahan tabel ms_role & ms_user
-- untuk sistem RBAC sesuai rekomendasi PRD
-- ============================================

-- Tabel Role
CREATE TABLE IF NOT EXISTS public.ms_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama character varying(50) NOT NULL UNIQUE,
    deskripsi character varying(256),
    permissions jsonb DEFAULT '[]'::jsonb,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);

-- Seed default roles
INSERT INTO public.ms_role (nama, deskripsi, permissions) VALUES
    ('super_admin', 'Akses penuh ke seluruh sistem', '["dashboard","master","stock","transaksi","pengaturan","laporan"]'),
    ('admin_gudang', 'Akses ke Master dan Stock saja', '["master","stock"]'),
    ('kasir', 'Akses ke Transaksi Penjualan saja', '["transaksi"]')
ON CONFLICT (nama) DO NOTHING;

-- Tabel User
CREATE TABLE IF NOT EXISTS public.ms_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(100) NOT NULL UNIQUE,
    nama_lengkap character varying(256) NOT NULL,
    password_hash character varying(256) NOT NULL,
    role character varying(50) NOT NULL DEFAULT 'kasir' REFERENCES public.ms_role(nama),
    is_active boolean DEFAULT true NOT NULL,
    last_login timestamp without time zone,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);

-- Seed default users (passwords hashed with bcrypt in production)
-- Default passwords: admin123, gudang123, kasir123
INSERT INTO public.ms_user (username, nama_lengkap, password_hash, role) VALUES
    ('admin', 'Super Admin', '$2b$10$placeholder_hash_admin', 'super_admin'),
    ('gudang', 'Admin Gudang', '$2b$10$placeholder_hash_gudang', 'admin_gudang'),
    ('kasir', 'Kasir 1', '$2b$10$placeholder_hash_kasir', 'kasir')
ON CONFLICT (username) DO NOTHING;

-- ============================================
-- Tambahan kolom metode_pembayaran pada tabel
-- trs_penjualan_hdr (rekomendasi PRD)
-- ============================================
ALTER TABLE public.trs_penjualan_hdr
    ADD COLUMN IF NOT EXISTS metode_pembayaran character varying(20) DEFAULT 'Tunai',
    ADD COLUMN IF NOT EXISTS total_harga integer DEFAULT 0;

-- ============================================
-- Tambahan kolom status pada tabel detail
-- untuk tracking barang serial terjual/tersedia
-- ============================================
ALTER TABLE public.ms_hp_dtl
    ADD COLUMN IF NOT EXISTS status character varying(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS warna character varying(256) DEFAULT NULL;

ALTER TABLE public.ms_hp_dtl_non_pajak
    ADD COLUMN IF NOT EXISTS status character varying(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS warna character varying(256) DEFAULT NULL;

ALTER TABLE public.ms_cctv_dtl
    ADD COLUMN IF NOT EXISTS status character varying(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS warna character varying(256) DEFAULT NULL;

-- ============================================
-- RPC Functions untuk mengurangi stok
-- (dibutuhkan oleh kurangiStok() di db.ts)
-- ============================================

CREATE OR REPLACE FUNCTION public.kurangi_qty_aksesoris(p_id bigint, p_qty integer)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE public.ms_aksesoris
    SET qty = qty - p_qty, update_time = now()
    WHERE id = p_id AND qty >= p_qty;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Stok tidak mencukupi atau barang tidak ditemukan';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.kurangi_qty_kuota(p_id bigint, p_qty integer)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE public.ms_kuota
    SET qty = qty - p_qty, update_time = now()
    WHERE id = p_id AND qty >= p_qty;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Stok tidak mencukupi atau barang tidak ditemukan';
    END IF;
END;
$$;
