-- ============================================================
-- MIGRATION: ADD SPAREPART CATEGORY
-- Run this script in Supabase: Dashboard → SQL Editor → New Query → Run
-- ============================================================

-- Create Table public.ms_sparepart
CREATE TABLE IF NOT EXISTS public.ms_sparepart (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier character varying(256) NOT NULL,
    barcode character varying(256) NOT NULL,
    merk character varying(256) NOT NULL,
    nama character varying(256) NOT NULL,
    qty integer NOT NULL DEFAULT 0,
    harga_modal integer NOT NULL DEFAULT 0,
    harga_jual integer NOT NULL DEFAULT 0,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_sparepart UNIQUE (supplier, merk, nama)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.ms_sparepart ENABLE ROW LEVEL SECURITY;

-- Allow all policy for anon and authenticated users
DROP POLICY IF EXISTS "allow_all" ON public.ms_sparepart;
CREATE POLICY "allow_all" ON public.ms_sparepart FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Create Function for decreasing qty
CREATE OR REPLACE FUNCTION public.kurangi_qty_sparepart(p_id bigint, p_qty integer)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE public.ms_sparepart
    SET qty = qty - p_qty, update_time = now()
    WHERE id = p_id AND qty >= p_qty;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Stok tidak mencukupi atau barang tidak ditemukan';
    END IF;
END;
$$;
