-- ============================================================
-- SETUP LENGKAP DATABASE KASIR SERIES untuk SUPABASE
-- Jalankan di: Supabase Dashboard → SQL Editor → New Query
-- Paste semua ini lalu klik RUN
-- ============================================================

-- ============================================================
-- STEP 1: CREATE TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ms_aksesoris (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier character varying(256) NOT NULL,
    barcode character varying(256) NOT NULL,
    merk character varying(256) NOT NULL,
    nama character varying(256) NOT NULL,
    qty integer NOT NULL DEFAULT 0,
    harga_modal integer NOT NULL DEFAULT 0,
    harga_jual integer NOT NULL DEFAULT 0,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_aksesoris UNIQUE (supplier, merk, nama)
);

CREATE TABLE IF NOT EXISTS public.ms_cctv_hdr (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier character varying(256) NOT NULL,
    merk character varying(256) NOT NULL,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_cctv_hdr UNIQUE (supplier, merk, nama)
);

CREATE TABLE IF NOT EXISTS public.ms_cctv_dtl (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idhdr bigint NOT NULL REFERENCES public.ms_cctv_hdr(id) ON DELETE CASCADE,
    sn_cctv character varying(256) NOT NULL,
    harga_modal integer NOT NULL DEFAULT 0,
    harga_jual integer NOT NULL DEFAULT 0,
    status character varying(20) DEFAULT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_cctv_dtl UNIQUE (sn_cctv)
);

CREATE TABLE IF NOT EXISTS public.ms_hp_hdr (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier character varying(256) NOT NULL,
    merk character varying(256) NOT NULL,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_hp_hdr UNIQUE (supplier, merk, nama)
);

CREATE TABLE IF NOT EXISTS public.ms_hp_dtl (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idhdr bigint NOT NULL REFERENCES public.ms_hp_hdr(id) ON DELETE CASCADE,
    imei character varying(256) NOT NULL,
    harga_jual integer NOT NULL DEFAULT 0,
    harga_modal integer NOT NULL DEFAULT 0,
    status character varying(20) DEFAULT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_hp_dtl UNIQUE (imei)
);

CREATE TABLE IF NOT EXISTS public.ms_hp_hdr_non_pajak (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier character varying(256) NOT NULL,
    merk character varying(256) NOT NULL,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_hp_hdr_non_pajak UNIQUE (supplier, merk, nama)
);

CREATE TABLE IF NOT EXISTS public.ms_hp_dtl_non_pajak (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idhdr bigint NOT NULL REFERENCES public.ms_hp_hdr_non_pajak(id) ON DELETE CASCADE,
    imei character varying(256) NOT NULL,
    harga_jual integer NOT NULL DEFAULT 0,
    harga_modal integer NOT NULL DEFAULT 0,
    status character varying(20) DEFAULT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_hp_dtl_non_pajak UNIQUE (imei)
);

CREATE TABLE IF NOT EXISTS public.ms_kuota (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier character varying(256) NOT NULL,
    barcode character varying(256) NOT NULL,
    operator character varying(256) NOT NULL,
    description character varying(256) NOT NULL,
    qty integer NOT NULL DEFAULT 0,
    harga_modal integer NOT NULL DEFAULT 0,
    harga_jual integer NOT NULL DEFAULT 0,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_kuota UNIQUE (supplier, operator, description)
);

CREATE TABLE IF NOT EXISTS public.ms_merk (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama character varying(256) NOT NULL,
    kategori character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_merk UNIQUE (nama, kategori)
);

CREATE TABLE IF NOT EXISTS public.ms_operator (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_operator UNIQUE (nama)
);

CREATE TABLE IF NOT EXISTS public.ms_supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_ms_supplier UNIQUE (nama)
);

CREATE TABLE IF NOT EXISTS public.trs_penjualan_hdr (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_invoice character varying(50) NOT NULL,
    customer character varying(256) NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    metode_pembayaran character varying(20) DEFAULT 'Tunai',
    total_harga integer DEFAULT 0,
    tanggal_penjualan timestamp without time zone DEFAULT now() NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_trs_penjualan_hdr UNIQUE (nomor_invoice)
);

CREATE TABLE IF NOT EXISTS public.trs_penjualan_dtl (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idhdr bigint NOT NULL REFERENCES public.trs_penjualan_hdr(id) ON DELETE CASCADE,
    idbarang bigint NOT NULL,
    kategori character varying(256) NOT NULL,
    code character varying(256) NOT NULL,
    nama_barang character varying(256) NOT NULL,
    qty integer NOT NULL DEFAULT 1,
    harga_modal integer NOT NULL DEFAULT 0,
    harga_jual integer NOT NULL DEFAULT 0,
    supplier character varying(256),
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_trs_penjualan_dtl UNIQUE (idhdr, code, nama_barang)
);

CREATE TABLE IF NOT EXISTS public.trs_pembelian_hdr (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_invoice character varying(256),
    supplier character varying(256) NOT NULL,
    tanggal_pembelian timestamp without time zone DEFAULT now() NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);

CREATE TABLE IF NOT EXISTS public.trs_pembelian_dtl (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idhdr bigint NOT NULL REFERENCES public.trs_pembelian_hdr(id) ON DELETE CASCADE,
    idbarang bigint NOT NULL,
    kategori character varying(256) NOT NULL,
    code character varying(256) NOT NULL,
    nama_barang character varying(256) NOT NULL,
    qty integer NOT NULL DEFAULT 1,
    harga_modal integer NOT NULL DEFAULT 0,
    harga_jual integer NOT NULL DEFAULT 0,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    CONSTRAINT uq_trs_pembelian_dtl UNIQUE (idhdr, code, nama_barang)
);

-- ============================================================
-- STEP 2: RPC FUNCTIONS (untuk kurangi stok)
-- ============================================================

CREATE OR REPLACE FUNCTION public.kurangi_qty_aksesoris(p_id bigint, p_qty integer)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE public.ms_aksesoris
    SET qty = qty - p_qty, update_time = now()
    WHERE id = p_id AND qty >= p_qty;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Stok tidak mencukupi atau barang tidak ditemukan';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.kurangi_qty_kuota(p_id bigint, p_qty integer)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE public.ms_kuota
    SET qty = qty - p_qty, update_time = now()
    WHERE id = p_id AND qty >= p_qty;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Stok tidak mencukupi atau barang tidak ditemukan';
    END IF;
END;
$$;

-- ============================================================
-- STEP 3: ENABLE RLS + ALLOW ALL (anon & authenticated)
-- ============================================================

ALTER TABLE public.ms_merk ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_merk;
CREATE POLICY "allow_all" ON public.ms_merk FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_operator ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_operator;
CREATE POLICY "allow_all" ON public.ms_operator FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_supplier ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_supplier;
CREATE POLICY "allow_all" ON public.ms_supplier FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_aksesoris ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_aksesoris;
CREATE POLICY "allow_all" ON public.ms_aksesoris FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_kuota ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_kuota;
CREATE POLICY "allow_all" ON public.ms_kuota FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_hp_hdr ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_hp_hdr;
CREATE POLICY "allow_all" ON public.ms_hp_hdr FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_hp_dtl ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_hp_dtl;
CREATE POLICY "allow_all" ON public.ms_hp_dtl FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_hp_hdr_non_pajak ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_hp_hdr_non_pajak;
CREATE POLICY "allow_all" ON public.ms_hp_hdr_non_pajak FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_hp_dtl_non_pajak ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_hp_dtl_non_pajak;
CREATE POLICY "allow_all" ON public.ms_hp_dtl_non_pajak FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_cctv_hdr ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_cctv_hdr;
CREATE POLICY "allow_all" ON public.ms_cctv_hdr FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.ms_cctv_dtl ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.ms_cctv_dtl;
CREATE POLICY "allow_all" ON public.ms_cctv_dtl FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.trs_penjualan_hdr ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.trs_penjualan_hdr;
CREATE POLICY "allow_all" ON public.trs_penjualan_hdr FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.trs_penjualan_dtl ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.trs_penjualan_dtl;
CREATE POLICY "allow_all" ON public.trs_penjualan_dtl FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.trs_pembelian_hdr ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.trs_pembelian_hdr;
CREATE POLICY "allow_all" ON public.trs_pembelian_hdr FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.trs_pembelian_dtl ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.trs_pembelian_dtl;
CREATE POLICY "allow_all" ON public.trs_pembelian_dtl FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- log_aktivitas
CREATE TABLE IF NOT EXISTS public.log_aktivitas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(256) NOT NULL,
    aksi character varying(50) NOT NULL,
    tabel character varying(100) NOT NULL,
    detail text NOT NULL,
    waktu timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.log_aktivitas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_all" ON public.log_aktivitas;
CREATE POLICY "allow_all" ON public.log_aktivitas FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
