--
-- PostgreSQL database dump
--



-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-06-14 09:08:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 18520)
-- Name: ms_aksesoris; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_aksesoris (
    id bigint NOT NULL,
    supplier character varying(256) NOT NULL,
    barcode character varying(256) NOT NULL,
    merk character varying(256) NOT NULL,
    nama character varying(256) NOT NULL,
    qty integer NOT NULL,
    harga_modal integer NOT NULL,
    harga_jual integer NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_aksesoris OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 18535)
-- Name: ms_aksesoris_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_aksesoris ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_aksesoris_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 18536)
-- Name: ms_cctv_dtl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_cctv_dtl (
    id bigint NOT NULL,
    idhdr bigint NOT NULL,
    sn_cctv character varying(256) NOT NULL,
    harga_modal integer NOT NULL,
    harga_jual integer NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_cctv_dtl OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 18548)
-- Name: ms_cctv_dtl_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_cctv_dtl ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_cctv_dtl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 18549)
-- Name: ms_cctv_hdr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_cctv_hdr (
    id bigint NOT NULL,
    supplier character varying(256) NOT NULL,
    merk character varying(256) NOT NULL,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_cctv_hdr OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 18560)
-- Name: ms_cctv_hdr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_cctv_hdr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_cctv_hdr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 18561)
-- Name: ms_hp_dtl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_hp_dtl (
    id bigint NOT NULL,
    idhdr bigint NOT NULL,
    imei character varying(256) NOT NULL,
    harga_jual integer NOT NULL,
    harga_modal integer NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_hp_dtl OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 18573)
-- Name: ms_hp_dtl_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_hp_dtl ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_hp_dtl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 18574)
-- Name: ms_hp_dtl_non_pajak; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_hp_dtl_non_pajak (
    id bigint NOT NULL,
    idhdr bigint NOT NULL,
    imei character varying(256) NOT NULL,
    harga_jual integer NOT NULL,
    harga_modal integer NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_hp_dtl_non_pajak OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 18586)
-- Name: ms_hp_dtl_non_pajak_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_hp_dtl_non_pajak ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_hp_dtl_non_pajak_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 18587)
-- Name: ms_hp_hdr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_hp_hdr (
    id bigint NOT NULL,
    supplier character varying(256) NOT NULL,
    merk character varying(256) NOT NULL,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_hp_hdr OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 18598)
-- Name: ms_hp_hdr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_hp_hdr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_hp_hdr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 18599)
-- Name: ms_hp_hdr_non_pajak; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_hp_hdr_non_pajak (
    id bigint NOT NULL,
    supplier character varying(256) NOT NULL,
    merk character varying(256) NOT NULL,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_hp_hdr_non_pajak OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 18610)
-- Name: ms_hp_hdr_non_pajak_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_hp_hdr_non_pajak ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_hp_hdr_non_pajak_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 18611)
-- Name: ms_kuota; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_kuota (
    id bigint NOT NULL,
    supplier character varying(256) NOT NULL,
    barcode character varying(256) NOT NULL,
    operator character varying(256) NOT NULL,
    description character varying(256) NOT NULL,
    qty integer NOT NULL,
    harga_modal integer NOT NULL,
    harga_jual integer NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_kuota OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 18626)
-- Name: ms_kuota_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_kuota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_kuota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 18627)
-- Name: ms_merk; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_merk (
    id bigint NOT NULL,
    nama character varying(256) NOT NULL,
    kategori character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_merk OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 18637)
-- Name: ms_merk_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_merk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_merk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 18638)
-- Name: ms_operator; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_operator (
    id bigint NOT NULL,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_operator OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 18647)
-- Name: ms_operator_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_operator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_operator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 18648)
-- Name: ms_supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ms_supplier (
    id bigint NOT NULL,
    nama character varying(256) NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.ms_supplier OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 18657)
-- Name: ms_supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ms_supplier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ms_supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 18658)
-- Name: trs_pembelian_dtl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trs_pembelian_dtl (
    id bigint NOT NULL,
    idhdr bigint NOT NULL,
    idbarang bigint NOT NULL,
    kategori character varying(256) NOT NULL,
    code character varying(256) NOT NULL,
    nama_barang character varying(256) NOT NULL,
    qty integer NOT NULL,
    harga_modal integer NOT NULL,
    harga_jual integer NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.trs_pembelian_dtl OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 18674)
-- Name: trs_pembelian_dtl_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trs_pembelian_dtl ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trs_pembelian_dtl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 18675)
-- Name: trs_pembelian_hdr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trs_pembelian_hdr (
    id bigint NOT NULL,
    no_invoice character varying(256),
    supplier character varying(256) NOT NULL,
    tanggal_pembelian timestamp without time zone DEFAULT now() NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.trs_pembelian_hdr OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 18688)
-- Name: trs_pembelian_hdr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trs_pembelian_hdr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trs_pembelian_hdr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 18689)
-- Name: trs_penjualan_dtl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trs_penjualan_dtl (
    id bigint NOT NULL,
    idhdr bigint NOT NULL,
    idbarang bigint NOT NULL,
    kategori character varying(256) NOT NULL,
    code character varying(256) NOT NULL,
    nama_barang character varying(256) NOT NULL,
    qty integer NOT NULL,
    harga_modal integer NOT NULL,
    harga_jual integer NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256),
    supplier character varying(256)
);


ALTER TABLE public.trs_penjualan_dtl OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 18705)
-- Name: trs_penjualan_dtl_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trs_penjualan_dtl ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trs_penjualan_dtl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 18706)
-- Name: trs_penjualan_hdr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trs_penjualan_hdr (
    id bigint NOT NULL,
    nomor_invoice character varying(50) NOT NULL,
    customer character varying(256) NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    tanggal_penjualan timestamp without time zone DEFAULT now() NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    create_by character varying(256),
    update_time timestamp without time zone,
    update_by character varying(256)
);


ALTER TABLE public.trs_penjualan_hdr OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 18720)
-- Name: trs_penjualan_hdr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trs_penjualan_hdr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trs_penjualan_hdr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4842 (class 2606 OID 18737)
-- Name: ms_aksesoris pk_ms_aksesoris; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_aksesoris
    ADD CONSTRAINT pk_ms_aksesoris PRIMARY KEY (id);


--
-- TOC entry 4846 (class 2606 OID 18739)
-- Name: ms_cctv_dtl pk_ms_cctv_dtl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_cctv_dtl
    ADD CONSTRAINT pk_ms_cctv_dtl PRIMARY KEY (id);


--
-- TOC entry 4850 (class 2606 OID 18741)
-- Name: ms_cctv_hdr pk_ms_cctv_hdr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_cctv_hdr
    ADD CONSTRAINT pk_ms_cctv_hdr PRIMARY KEY (id);


--
-- TOC entry 4854 (class 2606 OID 18743)
-- Name: ms_hp_dtl pk_ms_hp_dtl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_dtl
    ADD CONSTRAINT pk_ms_hp_dtl PRIMARY KEY (id);


--
-- TOC entry 4858 (class 2606 OID 18745)
-- Name: ms_hp_dtl_non_pajak pk_ms_hp_dtl_non_pajak; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_dtl_non_pajak
    ADD CONSTRAINT pk_ms_hp_dtl_non_pajak PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 18747)
-- Name: ms_hp_hdr pk_ms_hp_hdr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_hdr
    ADD CONSTRAINT pk_ms_hp_hdr PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 18749)
-- Name: ms_hp_hdr_non_pajak pk_ms_hp_hdr_non_pajak; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_hdr_non_pajak
    ADD CONSTRAINT pk_ms_hp_hdr_non_pajak PRIMARY KEY (id);


--
-- TOC entry 4870 (class 2606 OID 18751)
-- Name: ms_kuota pk_ms_kuota; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_kuota
    ADD CONSTRAINT pk_ms_kuota PRIMARY KEY (id);


--
-- TOC entry 4874 (class 2606 OID 18753)
-- Name: ms_merk pk_ms_merk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_merk
    ADD CONSTRAINT pk_ms_merk PRIMARY KEY (id);


--
-- TOC entry 4878 (class 2606 OID 18755)
-- Name: ms_operator pk_ms_operator; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_operator
    ADD CONSTRAINT pk_ms_operator PRIMARY KEY (id);


--
-- TOC entry 4882 (class 2606 OID 18757)
-- Name: ms_supplier pk_ms_supplier; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_supplier
    ADD CONSTRAINT pk_ms_supplier PRIMARY KEY (id);


--
-- TOC entry 4886 (class 2606 OID 18759)
-- Name: trs_pembelian_dtl pk_trs_pembelian_dtl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trs_pembelian_dtl
    ADD CONSTRAINT pk_trs_pembelian_dtl PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 18761)
-- Name: trs_pembelian_hdr pk_trs_pembelian_hdr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trs_pembelian_hdr
    ADD CONSTRAINT pk_trs_pembelian_hdr PRIMARY KEY (id);


--
-- TOC entry 4892 (class 2606 OID 18763)
-- Name: trs_penjualan_dtl pk_trs_penjualan_dtl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trs_penjualan_dtl
    ADD CONSTRAINT pk_trs_penjualan_dtl PRIMARY KEY (id);


--
-- TOC entry 4896 (class 2606 OID 18765)
-- Name: trs_penjualan_hdr pk_trs_penjualan_hdr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trs_penjualan_hdr
    ADD CONSTRAINT pk_trs_penjualan_hdr PRIMARY KEY (id);


--
-- TOC entry 4844 (class 2606 OID 18767)
-- Name: ms_aksesoris uq_ms_aksesoris; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_aksesoris
    ADD CONSTRAINT uq_ms_aksesoris UNIQUE (supplier, merk, nama);


--
-- TOC entry 4848 (class 2606 OID 18769)
-- Name: ms_cctv_dtl uq_ms_cctv_dtl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_cctv_dtl
    ADD CONSTRAINT uq_ms_cctv_dtl UNIQUE (sn_cctv);


--
-- TOC entry 4852 (class 2606 OID 18771)
-- Name: ms_cctv_hdr uq_ms_cctv_hdr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_cctv_hdr
    ADD CONSTRAINT uq_ms_cctv_hdr UNIQUE (supplier, merk, nama);


--
-- TOC entry 4856 (class 2606 OID 18773)
-- Name: ms_hp_dtl uq_ms_hp_dtl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_dtl
    ADD CONSTRAINT uq_ms_hp_dtl UNIQUE (imei);


--
-- TOC entry 4860 (class 2606 OID 18775)
-- Name: ms_hp_dtl_non_pajak uq_ms_hp_dtl_non_pajak; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_dtl_non_pajak
    ADD CONSTRAINT uq_ms_hp_dtl_non_pajak UNIQUE (imei);


--
-- TOC entry 4864 (class 2606 OID 18777)
-- Name: ms_hp_hdr uq_ms_hp_hdr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_hdr
    ADD CONSTRAINT uq_ms_hp_hdr UNIQUE (supplier, merk, nama);


--
-- TOC entry 4868 (class 2606 OID 18779)
-- Name: ms_hp_hdr_non_pajak uq_ms_hp_hdr_non_pajak; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_hdr_non_pajak
    ADD CONSTRAINT uq_ms_hp_hdr_non_pajak UNIQUE (supplier, merk, nama);


--
-- TOC entry 4872 (class 2606 OID 18781)
-- Name: ms_kuota uq_ms_kuota; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_kuota
    ADD CONSTRAINT uq_ms_kuota UNIQUE (supplier, operator, description);


--
-- TOC entry 4876 (class 2606 OID 18783)
-- Name: ms_merk uq_ms_merk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_merk
    ADD CONSTRAINT uq_ms_merk UNIQUE (nama, kategori);


--
-- TOC entry 4880 (class 2606 OID 18785)
-- Name: ms_operator uq_ms_operator; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_operator
    ADD CONSTRAINT uq_ms_operator UNIQUE (nama);


--
-- TOC entry 4884 (class 2606 OID 18787)
-- Name: ms_supplier uq_ms_supplier; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_supplier
    ADD CONSTRAINT uq_ms_supplier UNIQUE (nama);


--
-- TOC entry 4888 (class 2606 OID 18789)
-- Name: trs_pembelian_dtl uq_trs_pembelian_dtl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trs_pembelian_dtl
    ADD CONSTRAINT uq_trs_pembelian_dtl UNIQUE (idhdr, code, nama_barang);


--
-- TOC entry 4894 (class 2606 OID 18791)
-- Name: trs_penjualan_dtl uq_trs_penjualan_dtl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trs_penjualan_dtl
    ADD CONSTRAINT uq_trs_penjualan_dtl UNIQUE (idhdr, code, nama_barang);


--
-- TOC entry 4898 (class 2606 OID 18793)
-- Name: trs_penjualan_hdr uq_trs_penjualan_hdr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trs_penjualan_hdr
    ADD CONSTRAINT uq_trs_penjualan_hdr UNIQUE (nomor_invoice);


--
-- TOC entry 4904 (class 2620 OID 18794)
-- Name: trs_pembelian_dtl trg_pembelian; Type: TRIGGER; Schema: public; Owner: postgres
--



--
-- TOC entry 4905 (class 2620 OID 18795)
-- Name: trs_penjualan_dtl trg_penjualan; Type: TRIGGER; Schema: public; Owner: postgres
--



--
-- TOC entry 4899 (class 2606 OID 18796)
-- Name: ms_cctv_dtl fk_ms_cctv_dtl_hdr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_cctv_dtl
    ADD CONSTRAINT fk_ms_cctv_dtl_hdr FOREIGN KEY (idhdr) REFERENCES public.ms_cctv_hdr(id) ON DELETE CASCADE;


--
-- TOC entry 4900 (class 2606 OID 18801)
-- Name: ms_hp_dtl fk_ms_hp_dtl_hdr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_dtl
    ADD CONSTRAINT fk_ms_hp_dtl_hdr FOREIGN KEY (idhdr) REFERENCES public.ms_hp_hdr(id) ON DELETE CASCADE;


--
-- TOC entry 4901 (class 2606 OID 18806)
-- Name: ms_hp_dtl_non_pajak fk_ms_hp_dtl_hdr_non_pajak; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ms_hp_dtl_non_pajak
    ADD CONSTRAINT fk_ms_hp_dtl_hdr_non_pajak FOREIGN KEY (idhdr) REFERENCES public.ms_hp_hdr_non_pajak(id) ON DELETE CASCADE;


--
-- TOC entry 4902 (class 2606 OID 18811)
-- Name: trs_pembelian_dtl fk_trs_pembelian_dtl_hdr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trs_pembelian_dtl
    ADD CONSTRAINT fk_trs_pembelian_dtl_hdr FOREIGN KEY (idhdr) REFERENCES public.trs_pembelian_hdr(id) ON DELETE CASCADE;


--
-- TOC entry 4903 (class 2606 OID 18816)
-- Name: trs_penjualan_dtl fk_trs_penjualan_dtl_hdr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trs_penjualan_dtl
    ADD CONSTRAINT fk_trs_penjualan_dtl_hdr FOREIGN KEY (idhdr) REFERENCES public.trs_penjualan_hdr(id) ON DELETE CASCADE;


-- Completed on 2026-06-14 09:08:46

--
-- PostgreSQL database dump complete
--


